### PR TITLE
Fix/81 routing

### LINKED ISSUE #81: improve route parameter handling and error reporting
## description

when defining routes with overlapping patterns, the order of definition matters.

say we have these 2 endpoints and their respective handlers:
- `/app/:id` -> `app_get`
- `/app/:id/hello` -> `app_hello`

the expected behaviour would be:
- if you define `/app/:id` before `/app/:id/hello`, requests to `/app/:id/hello` would be handled by `app_get` because `/:id` will match anything after `/app/`.
- if you define `/app/:id/hello` **before** `/app/:id`, it should work well because a more specific route will be matched first and then `/app/:id` would handle any other requests.

## the issue

currently in ambiorix when you define `/app/:id` first, visiting `/app/:id/hello` *silently* returns a 500 to the client with:

```
ERROR: subscript out of bounds
```

this error:
- escapes the global error handler, making debugging difficult
- fails to provide clear feedback about what went wrong

## reprex

```r
library(ambiorix)
library(htmltools)

home_get <- \(req, res) {
  html <- tags$h3("hello, world!")
  res$send(html)
}

app_get <- \(req, res) {
  html <- tags$h3("you're visiting app with id:", req$params$id)
  res$send(html)
}

app_hello <- \(req, res) {
  msg <- sprintf(
    "app with id '%s' says hello",
    req$params$id
  )
  html <- tags$h3(msg)
  res$send(html)
}

error_handler <- \(req, res, error){
  res$status(500L)
  res$send("There was a server error :(")
}

app <- Ambiorix$new(port = 5000L)$
  set_error(error_handler)$
  get("/", home_get)$
  get("/app/:id", app_get)$ # MUST be defined AFTER '/app/:id/hello'
  get("/app/:id/hello", app_hello)

app$start()
```

## question

what would be the best way to handle this?
1. handling `/app/:id/hello` correctly (based on route order)?
2. throwing a clearer, louder error?
3. something else maybe?

would like to hear your thoughts on this @JohnCoene

### PR DESCRIPTION
**Pull request by JohnCoene**
This should fix #81

### CODE REVIEW

File: R/request.R [hunk 1]
```diff
@@ -226,6 +226,9 @@ set_params <- function(path, route = NULL){
   nms <- c()
   pms <- list()
   for(i in seq_along(path_split)){
+    if(i > length(route$components))
+      next
```
Comment (kennedymwavu) [inline R/request.R:230]: since we are not mutating `route$components`, shouldn't this be a `break` instead of `next`? because once the condition `i > length(route$components` is `TRUE`, it will be `TRUE` for all subsequent i's.

File: R/routing.R [hunk 2]
```diff
@@ -484,7 +484,16 @@ Routing <- R6::R6Class(
...
-          request$params <- set_params(request$PATH_INFO, private$.routes[[i]]$route)
+          request$params <- tryCatch(
+            set_params(request$PATH_INFO, private$.routes[[i]]$route),
+            error = function(error){
+              error
+            }
+          )
+
+          if(inherits(request$params, "error")){
+            return(private$.routes[[i]]$error(request, res, response))
```
Comment (kennedymwavu) [inline R/routing.R:495]: since we're dealing with the `request$params` object, this return value should be:

```r
private$.routes[[i]]$error(request, res, request$params)
```

**Review by kennedymwavu — CHANGES_REQUESTED** [review]
this fixes the issue. please have a look at the 2 comments i left.

**Comment by JohnCoene** [comment]
Yes indeed, thanks for that!

**Review by kennedymwavu — APPROVED** [review]
lgtm!
